# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.9.4-amazoncorretto-11-al2023
    steps:
      - checkout
      - run:
          name: "build code"
          command: |
            mvn clean install -DskipTests

  unit-test:
    docker:
      - image: maven:3.9.4-amazoncorretto-11-al2023
    steps:
      - checkout
      - run:
          name: "build code"
          command: |
            mvn test

  push-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Build docker image
          command: |
            docker build  -t huynhduy1420021/devops-project-5:${CIRCLE_WORKFLOW_ID:0:7} .
      - deploy:
          name: Push Docker image 
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD            
            docker push "huynhduy1420021/devops-project-5:${CIRCLE_WORKFLOW_ID:0:7}"

workflows:
  say-hello-workflow:
    jobs:
      - build
      - unit-test:
          requires: [build]
      - push-image:
          requires: [unit-test]
